spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: spring-cloud-learn-config-dev
---
spring:
  profiles: rest   #测试环境
  application: 
    name: spring-cloud-learn-config-rest
#  请保存为UTF-8格式
 
 
