spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201 
spring:
  profiles: dev
  application: 
    name: spring-cloud-learn-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dev.com:7777/eureka/   
---
server: 
  port: 8202 
spring:
  profiles: rest
  application: 
    name: spring-cloud-learn-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-rest.com:8888/eureka/
 
